apiVersion: v1
kind: ConfigMap
metadata:
  name: ids-config
  namespace: zlc
data:
  config.yaml: |
    cache:
      driver: memory # supports memory or redis
      host: localhost # redis host
      port: 6379 # redis port
      password: "" # redis password
      db: 0 # redis database
      default_expiration: # set default expiration, in seconds for different types
        airports: 3600 # 1 hour, airport cache (includes METARs, TAFs, SIA, etc.)
        charts: 86400 # 1 day, chart cache

    database:
      driver: mysql # supports mysql and postgres
      host: {{.DB_HOST | default "mysql.mysql.svc.cluster.local"}}
      port: {{.DB_PORT | default "3306"}}
      username: {{.DB_USER | default "root"}}
      password: {{.DB_PASSWORD | default "root"}}
      database_name: idsv2 # database name
      auto_migrate: true # auto migrate database on startup
      ca_cert: {{.DB_CA_CERT | default ""}}

    facility:
      identifier: ZLC # FAA Facility Identifier
      name: Salt Lake City ARTCC # Facility Name
      adh: # ADH Partnership configuration
        api_base: https://api.zlcartcc.org # Base URL for ADH API
        rostered: true # Allow only rostered controllers

    oauth:
      Provider: adh # OAuth Provider, supports adh or vatsim
      base_url: https://auth.zlcartcc.org # Base URL for OAuth Provider
      client_id: "{{.OAUTH_CLIENT_ID | default "zlc"}}"
      client_secret: "{{.OAUTH_CLIENT_SECRET | default "zlc"}}"
      my_base_URL: "{{.OAUTH_MY_BASE_URL | default "https://api.dev.zlcartcc.net" }}" # Base URL for this application
      endpoints: # OAuth Endpoints
        authorize: /oauth/authorize # OAuth Authorize
        token: /oauth/token # OAuth Token
        userinfo: /v1/info # OAuth Userinfo

    server:
      ip: "" # IP to bind to (if needed, leave empty if not)
      port: 3000 # Port to listen on
      mode: h2c # Server mode, supports plain, https (h2), h2c
      # for https, expects SSL_CERT and SSL_KEY env vars to be set

    session:
      hash_key: "{{.SESSION_KEY | default "zlc_session"}}"
      block_key: "{{.SESSION_KEY | default "zlc_session"}}"
      name: "{{.SESSION_NAME | default "zlc_session"}}"
      domain: "{{.SESSION_DOMAIN | default ".zlcartcc.org"}}"
      path: "/"
      max_age: 86400 # Session Max Age, in seconds
      secure: false # Session Secure
      http_only: true # Session HTTP Only
  airports.json: |
    [
      "SLC",
      "PVU",
      "PIH",
      "MUO",
      "BOI",
      "BZN",
      "BIL",
      "HLN",
      "HLN",
      "LVM"
    ]
