apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: adhp/zlc-frontend
  newName: adhp/frontend
  newTag: zlc-main-b24cd0d
- name: zlcartcc/api
  newName: adhp/api
  newTag: dev-e719181
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
