apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-zlcartcc-org-tls
spec:
  dnsNames:
  - www.zlcartcc.org
  - zlcartcc.org
  - new.zlcartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-zlcartcc-org-tls
