apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/ingress.yaml
- discord/service.yaml
- mysql-backup/cronjob.yaml
- bot/deployment.yaml
- chart-parser/cronjob.yaml
images:
- name: adhp/zlc-frontend
  newName: adhp/frontend
  newTag: zlc-v1.7.1690939170.32-7966425
- name: zlcartcc/api
  newName: adhp/api
  newTag: main-5bedc84
- name: zlcartcc/auth
  newName: adhp/auth
  newTag: 72032a6
- name: zlcartcc/bot
  newName: adhp/bot
  newTag: main-89bb762
