apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discord-zlcartcc-org-tls
spec:
  dnsNames:
  - discord.zlcartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-discord-zlcartcc-org
