apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-zlcartcc-org-tls
spec:
  dnsNames:
  - auth.zlcartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-auth-zlcartcc-org
